In [1]:
import requests
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [55]:
# from dateutil.parser import parse

### HYDRO DATA

In [2]:
# Reading Hydro Data
hydro_url = "http://127.0.0.1:5000/api/v1.0/hydro"
hydro_request = requests.get(hydro_url)
hydro = hydro_request.json()

print (hydro)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [3]:
Date = []
Hour = []
Demanded_Toronto = []
Weekday = []

for i in range (len(hydro)):
    Date.append(hydro[i]['date'])
    Hour.append(hydro[i]['hour'])
    Demanded_Toronto.append(hydro[i]['demanded_toronto'])
    Weekday.append(hydro[i]['weekday'])
    
    
    
hydro_df = pd.DataFrame({'Date': Date,
                           'Hour': Hour,
                           'Demanded_Toronto': Demanded_Toronto,
                           'Weekday': Weekday})

In [4]:
hydro_df

                                 Date  Hour  Demanded_Toronto  Weekday
0       Thu, 01 May 2003 00:00:00 GMT     1              4422     True
1       Thu, 01 May 2003 00:00:00 GMT     2              4340     True
2       Thu, 01 May 2003 00:00:00 GMT     3              4281     True
3       Thu, 01 May 2003 00:00:00 GMT     4              4281     True
4       Thu, 01 May 2003 00:00:00 GMT     5              4469     True
...                               ...   ...               ...      ...
150763  Sat, 11 Jul 2020 00:00:00 GMT    20              6601    False
150764  Sat, 11 Jul 2020 00:00:00 GMT    21              6442    False
150765  Sat, 11 Jul 2020 00:00:00 GMT    22              6278    False
150766  Sat, 11 Jul 2020 00:00:00 GMT    23              5928    False
150767  Sat, 11 Jul 2020 00:00:00 GMT    24              5528    False

[150768 rows x 4 columns]

### WEATHER DATA

In [5]:
# Reading Weather Data
weather_url = "http://127.0.0.1:5000/api/v1.0/weather"
weather_request = requests.get(weather_url)
weather = weather_request.json()

print (weather)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [6]:
Date = []
Hour = []
Clouds = []
UTC_Date =[]
Feels_Like = []
Humidity = []
Pressure = []
Temperature = []
Temp_Max = []
Temp_Min = []
TimeZone = []
Weather_Description = []
Weather_Main = []
Wind_Direction = []
Wind_Speed = []

for i in range (len(weather)):
    Date.append(weather[i]['date'])
    Hour.append(weather[i]['hour'])
    Clouds.append(weather[i]['clouds_all'])
    UTC_Date.append(weather[i]['dt'])
    Feels_Like.append(weather[i]['feels_like'])
    Humidity.append(weather[i]['humidity'])
    Pressure.append(weather[i]['pressure'])
    Temperature.append(weather[i]['temp'])
    Temp_Max.append(weather[i]['temp_max'])
    Temp_Min.append(weather[i]['temp_min'])
    TimeZone.append(weather[i]['timezone'])
    Weather_Description.append(weather[i]['weather_description'])
    Weather_Main.append(weather[i]['weather_main'])
    Wind_Direction.append(weather[i]['wind_deg'])
    Wind_Speed.append(weather[i]['wind_speed'])
    
    
weather_df = pd.DataFrame({'Date': Date,
                           'Hour': Hour,
                           'Clouds': Clouds,
                           'UTC_Date': UTC_Date,
                           'Feels_Like': Feels_Like,
                           'Humidity': Humidity,                          
                           'Pressure': Pressure,                          
                           'Temperature': Temperature,
                           'Temp_Max': Temp_Max,
                           'Temp_Min': Temp_Min,
                           'TimeZone': TimeZone,
                           'Weather_Description': Weather_Description,
                           'Weather_Main': Weather_Main,
                           'Wind_Direction': Wind_Direction,
                           'Wind_Speed': Wind_Speed                          
                          })

In [7]:
weather_df

,Date,Hour,Clouds,UTC_Date,Feels_Like,Humidity,Pressure,Temperature,Temp_Max,Temp_Min,TimeZone,Weather_Description,Weather_Main,Wind_Direction,Wind_Speed
0,"Sun, 05 Jan 2003 00:00:00 GMT",5,90.0,1.041743e+09,-7.19,79.0,1017.0,-2.36,-0.80,-5.06,-18000.0,overcast clouds,Clouds,280.0,3.1
1,"Sun, 05 Jan 2003 00:00:00 GMT",6,90.0,1.041746e+09,-8.69,71.0,1017.0,-2.33,-0.80,-4.55,-18000.0,overcast clouds,Clouds,280.0,5.1
2,"Sun, 05 Jan 2003 00:00:00 GMT",7,90.0,1.041750e+09,-6.68,73.0,1017.0,-2.44,-1.10,-4.74,-18000.0,overcast clouds,Clouds,300.0,2.1
3,"Sun, 05 Jan 2003 00:00:00 GMT",8,90.0,1.041754e+09,-7.42,68.0,1017.0,-2.72,-1.20,-5.45,-18000.0,overcast clouds,Clouds,280.0,2.6
4,"Sun, 05 Jan 2003 00:00:00 GMT",9,90.0,1.041757e+09,-7.76,73.0,1017.0,-3.43,-1.20,-6.89,-18000.0,overcast clouds,Clouds,250.0,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154380,"Sun, 12 Jul 2020 00:00:00 GMT",19,90.0,1.594580e+09,28.48,78.0,998.0,26.25,28.89,23.00,-14400.0,light rain,Rain,160.0,3.6
154381,"Sun, 12 Jul 2020 00:00:00 GMT",20,40.0,1.594584e+09,27.91,69.0,1005.0,26.07,27.22,24.13,-14400.0,scattered clouds,Clouds,180.0,2.6
154382,"Sun, 12 Jul 2020 00:00:00 GMT",21,40.0,1.594588e+09,26.42,69.0,999.0,25.52,27.78,22.78,-14400.0,scattered clouds,Clouds,230.0,3.6
154383,"Sun, 12 Jul 2020 00:00:00 GMT",22,75.0,1.594591e+09,23.92,61.0,1000.0,24.84,27.22,22.22,-14400.0,broken clouds,Clouds,320.0,4.6
154384,"Sun, 12 Jul 2020 00:00:00 GMT",23,1.0,1.594595e+09,22.33,60.0,1006.0,24.01,25.00,22.22,-14400.0,sky is clear,Clear,330.0,5.1

In [108]:
combined_df = pd.merge(weather_df, hydro_df, on= ['Date', 'Hour'], how="inner")

In [109]:
print(len(weather_df))
print(len(hydro_df))
print(len(combined_df))

154385
150768
145271

In [110]:
# combined_df["Date"] = (combined_df["Date"].str.split(" ", n = 1, expand = True))[1]

# combined_df['Date'] = combined_df['Date'].str.slice(0, 11)


combined_df.head(10)

,Date,Hour,Clouds,UTC_Date,Feels_Like,Humidity,Pressure,Temperature,Temp_Max,Temp_Min,TimeZone,Weather_Description,Weather_Main,Wind_Direction,Wind_Speed,Demanded_Toronto,Weekday
0,"Thu, 01 May 2003 00:00:00 GMT",1,90.0,1.051751e+09,1.21,49.0,1015.0,7.52,9.0,3.32,-14400.0,overcast clouds,Clouds,80.0,5.7,4422,True
1,"Thu, 01 May 2003 00:00:00 GMT",2,90.0,1.051754e+09,1.53,52.0,1015.0,7.03,8.0,3.52,-14400.0,moderate rain,Rain,50.0,4.6,4340,True
2,"Thu, 01 May 2003 00:00:00 GMT",3,90.0,1.051758e+09,-0.39,65.0,1014.0,6.57,7.7,3.63,-14400.0,light rain,Rain,50.0,7.2,4281,True
3,"Thu, 01 May 2003 00:00:00 GMT",4,90.0,1.051762e+09,-1.47,56.0,1013.0,6.80,8.0,3.65,-14400.0,overcast clouds,Clouds,70.0,8.7,4281,True
4,"Thu, 01 May 2003 00:00:00 GMT",5,20.0,1.051765e+09,1.63,65.0,1012.0,6.74,8.0,3.73,-14400.0,few clouds,Clouds,90.0,4.6,4469,True
5,"Thu, 01 May 2003 00:00:00 GMT",6,20.0,1.051769e+09,3.35,63.0,1012.0,7.08,8.6,3.56,-14400.0,light rain,Rain,60.0,2.6,4951,True
6,"Thu, 01 May 2003 00:00:00 GMT",7,20.0,1.051772e+09,2.66,75.0,1012.0,6.45,7.0,3.07,-14400.0,light rain,Rain,80.0,3.1,5692,True
7,"Thu, 01 May 2003 00:00:00 GMT",8,20.0,1.051776e+09,2.48,75.0,1012.0,6.29,7.0,2.55,-14400.0,light rain,Rain,80.0,3.1,6105,True
8,"Thu, 01 May 2003 00:00:00 GMT",9,90.0,1.051780e+09,2.03,75.0,1010.0,5.90,7.0,2.22,-14400.0,light rain,Rain,80.0,3.1,6244,True
9,"Thu, 01 May 2003 00:00:00 GMT",10,90.0,1.051783e+09,2.27,75.0,1010.0,6.11,7.0,2.57,-14400.0,light rain,Rain,80.0,3.1,6323,True

In [111]:
combined_df = combined_df.drop(['Date'], axis =1)

X = combined_df.drop(['Demanded_Toronto'], axis=1)
y = combined_df["Demanded_Toronto"].values.reshape(-1, 1)
print(X.shape, y.shape)

(145271, 15) (145271, 1)

In [112]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [118]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(X_train)
encoded_X_train = label_encoder.transform(X_train)
encoded_X_test = label_encoder.transform(X_test)

ValueError: bad input shape (145271, 15)

In [113]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# model = LinearRegression()
# model.fit(X_train, y_train)
# training_score = model.score(X_train, y_train)
# testing_score = model.score(X_test, y_test)

X_scaler = StandardScaler().fit(X_train)

# print(f"Training Score: {training_score}")
# print(f"Testing Score: {testing_score}")

ValueError: could not convert string to float: 'scattered clouds'

In [74]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

ValueError: bad input shape (108953, 16)

In [86]:
model.fit(encoded_X_train, y_train)

NameError: name 'encoded_X_train' is not defined

In [ ]:
score = model.score(encoded_X_test, y_test)
print(f"R2 Score: {score}")